lib/iris_web/router.ex
defmodule IrisWeb.Router do
  use IrisWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", IrisWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    get "/settings", PageController, :settings
    resources "/users", UserController
    resources "/devices", DeviceController

    get "/signup", RegistrationController, :signup
    post "/signup", RegistrationController, :signup

    get "/login", SessionController, :login
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
  end

  scope "/api", IrisWeb do
     pipe_through :api

    resources "/services", ServiceController, except: [:new, :edit]
    resources "/messages", MessageController
  end
end

lib/iris_web/views/layout_view.ex
defmodule IrisWeb.LayoutView do
  use IrisWeb, :view

  alias Iris.User

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end

  def current_user_is_admin?(conn) do
    user = current_user(conn)
    User.is_admin?(user)
  end

end

lib/iris_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Iris</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <%= render "nav.html", assigns %>
    <div class="col-12" style="height:50px;"></div>
    <%= render "messages.html", assigns %>
    <div class="container">
      <%= render @view_module, @view_template, assigns %>
      <div class="col-12" style="height:50px;"></div>
      <%= render "footer.html", assigns %>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/iris_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>
    <p>Hello!</p>
    <%= render @view_module, @view_template, assigns %>
    <p>- The Iris Team.</p>
  </body>
</html>

lib/iris_web/templates/layout/email.text.eex
Hello!

<%= render @view_module, @view_template, assigns %>

- The Iris Team.

lib/iris_web/templates/layout/footer.html.eex
<footer id="footer" class="navbar fixed-bottom bg-faded">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
          <a href="https://github.com/JosKar/iris_server">Iris version <%= :application.get_key(:iris, :vsn) |> elem(1) %></a>
      </div>
      <div class="col-lg-6 text-right">
        <p>Released under the <a href="#">MIT License</a>.</p>
      </div>
    </div>
  </div>
</footer>

lib/iris_web/templates/layout/messages.html.eex
<div class="container">
  <%= if info = get_flash(@conn, :info) do %>
  <div class="row">
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Success!</h4>
      <p><%= info %></p>
    </div>
  </div>
  <% end %>
  <% if error = get_flash(@conn, :error) do %>
  <div class="row">
    <div class="alert alert-dismissible alert-danger">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Error!</h4>
      <p><%= error %></p>
    </div>
  </div>
  <% end %>
</div>

lib/iris_web/templates/layout/nav.html.eex
<div class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <a href="/" class="navbar-brand">Iris</a>

      <%
        user = current_user(@conn)
      %>
      <ul class="nav navbar-nav ml-auto">
        <%= if user do %>
          <li class="nav-item">
            <%= link "Message", to: page_path(@conn, :dashboard), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Devices", to: device_path(@conn, :index), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Applications", to: service_path(@conn, :index), class: "nav-link" %>
          </li>
          <%= if current_user_is_admin?(@conn) do %>
            <li class="nav-item">
              <%= link "Users", to: user_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "Settings", to: page_path(@conn, :settings), class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link "Logout", to: session_path(@conn, :logout), class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link "Login", to: session_path(@conn, :login), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Signup", to: registration_path(@conn, :signup), class: "nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>